In [2]:
import numpy as np

In [9]:
mat_1 = [[x for x in range(10)] for x in range(10)]
mat_2 = [[x+5 for x in range(10)] for x in range(10)]
print(mat_1)
print(mat_2)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]
[[5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14]]


In [10]:
mat_1 = np.array(mat_1) 
mat_2 = np.array(mat_2) 
print(mat_1)
print(mat_2)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]]


In [11]:
mat_1+mat_2

array([[ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])

In [12]:
mat_1.T

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [13]:
mat_1.dot(mat_2)

array([[225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630]])

In [14]:
mat_1*mat_2

array([[  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126]])

In [16]:
mat_1.reshape((5, 20))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [20]:
from numpy import genfromtxt
csvData = genfromtxt('MOCK_DATA.csv', delimiter=',', dtype=str)
print(csvData)

[['id' 'first_name' 'last_name' 'email' 'gender' 'ip_address']
 ['1' 'Eustace' 'Gosker' 'egosker0@etsy.com' 'Male' '171.86.34.204']
 ['2' 'Meggi' 'Burns' 'mburns1@columbia.edu' 'Female' '62.204.187.249']
 ...
 ['998' 'Gustave' 'Vernham' 'gvernhamrp@earthlink.net' 'Male'
  '5.198.223.149']
 ['999' 'Joice' 'Wearne' 'jwearnerq@wufoo.com' 'Female' '101.118.48.32']
 ['1000' 'Rooney' 'Castellaccio' 'rcastellacciorr@nyu.edu' 'Male'
  '113.81.181.76']]
