In [ ]:
import numpy as np

In [ ]:
mat_1 = [[x for x in range(10)] for x in range(10)]
mat_2 = [[x+5 for x in range(10)] for x in range(10)]
print(mat_1)
print(mat_2)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]
[[5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14], [5, 6, 7, 8, 9, 10, 11, 12, 13, 14]]


In [ ]:
mat_1 = np.array(mat_1) 
mat_2 = np.array(mat_2) 
print(mat_1)
print(mat_2)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 5  6  7  8  9 10 11 12 13 14]]


In [ ]:
mat_1+mat_2

array([[ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23],
       [ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23]])

In [ ]:
mat_1.T

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [ ]:
mat_1.dot(mat_2)

array([[225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630],
       [225, 270, 315, 360, 405, 450, 495, 540, 585, 630]])

In [ ]:
mat_1*mat_2

array([[  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126],
       [  0,   6,  14,  24,  36,  50,  66,  84, 104, 126]])

In [ ]:
mat_1.reshape((5, 20))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [2]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip
!unzip AirQualityUCI.zip

--2020-08-17 03:22:54--  https://archive.ics.uci.edu/ml/machine-learning-databases/00360/AirQualityUCI.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1543989 (1.5M) [application/x-httpd-php]
Saving to: ‘AirQualityUCI.zip’

AirQualityUCI.zip   100%[===================>]   1.47M  1.89MB/s    in 0.8s    

2020-08-17 03:22:55 (1.89 MB/s) - ‘AirQualityUCI.zip’ saved [1543989/1543989]



In [10]:
import pandas as pd
data = pd.read_csv('AirQualityUCI.csv',sep=';')

In [11]:
data.head()

Date      Time CO(GT)  ...      AH  Unnamed: 15 Unnamed: 16
0  10/03/2004  18.00.00    2,6  ...  0,7578          NaN         NaN
1  10/03/2004  19.00.00      2  ...  0,7255          NaN         NaN
2  10/03/2004  20.00.00    2,2  ...  0,7502          NaN         NaN
3  10/03/2004  21.00.00    2,2  ...  0,7867          NaN         NaN
4  10/03/2004  22.00.00    1,6  ...  0,7888          NaN         NaN

[5 rows x 17 columns]